---
- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.30.0/prometheus-2.30.0.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes
    creates: /opt/prometheus

- name: Create Prometheus directory
  file:
    path: /opt/prometheus
    state: directory

- name: Set up Prometheus user
  user:
    name: prometheus
    system: yes

- name: Copy Prometheus files
  copy:
    src: /opt/prometheus-2.30.0.linux-amd64/
    dest: /opt/prometheus
    remote_src: yes

- name: Set permissions on Prometheus directory
  file:
    path: /opt/prometheus
    owner: prometheus
    group: prometheus

#- name: Create a systemd service for Prometheus
#  template:
#    src: prometheus.service,j2
#    dest: /etc/systemd/system/prometheus.service

- name: Start and enable Prometheus service
  service:
    name: prometheus
    enabled: yes
    state: started
